import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-webpack5';
import { fn } from 'storybook/test';

import { Media } from 'hootsuite-bento';

const meta = {
  title: 'Bento/Media',
  component: Media,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
  argTypes: {
    onPress: {
      options: ['undefined', 'function'],
      mapping: {
        undefined: undefined,
        function: fn(),
      },
    },
    actions: {
      options: ['none', 'one', 'three'],
      mapping: {
        none: undefined,
        one: [
          {
            iconProps: { name: 'file_download' },
            tooltip: 'Download',
          },
        ],
        three: [
          {
            iconProps: { name: 'file_download' },
            tooltip: 'Download',
          },
          {
            iconProps: { name: 'repeat' },
            tooltip: 'Replace',
          },
          {
            iconProps: { name: 'delete' },
            tooltip: 'Delete',
          },
        ],
      },
    },
    style: { control: 'object' },
  },
  args: {
    src: 'https://picsum.photos/400/300',
    alt: 'A random image generated by picsum.photos',
    objectFit: 'scale-down',
  },
} satisfies Meta<typeof Media>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Base: Story = {};

export const WithError: Story = {
  args: { src: 'https://example.com/invalid-image.jpg' },
};

export const VideoPreview: Story = {
  args: {
    duration: 1505,
    onPress: fn(),
  },
};

export const SingleAction: Story = {
  args: {
    actions: [
      {
        iconProps: { name: 'file_download' },
        tooltip: 'Download',
      },
    ],
  },
};
