import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-webpack5';
import type { MediaGridProps } from 'hootsuite-bento';
import { fn } from 'storybook/test';

import { MediaGrid } from 'hootsuite-bento';

const examples: MediaGridProps['media'] = [
  {
    src: 'https://picsum.photos/400/300?1',
    alt: 'A random image generated by picsum.photos',
    id: '1',
  },
  {
    src: 'https://picsum.photos/300/400?2',
    alt: 'A random image generated by picsum.photos',
    id: '2',
  },
  {
    src: 'https://picsum.photos/300?3',
    alt: 'A random image generated by picsum.photos',
    id: '3',
  },
  {
    src: 'https://picsum.photos/50?4',
    alt: 'A random image generated by picsum.photos',
    id: '4',
  },
  {
    src: 'https://picsum.photos/400/300?5',
    alt: 'A random image generated by picsum.photos',
    id: '5',
  },
  {
    src: 'https://picsum.photos/300/400?6',
    alt: 'A random image generated by picsum.photos',
    id: '6',
  },
];

const meta = {
  title: 'Bento/MediaGrid',
  component: MediaGrid,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
  argTypes: {
    style: { control: 'object' },
    media: {
      options: ['0', '1', '2', '3', '4', '6'],
      control: { type: 'inline-radio' },
      mapping: {
        '0': [],
        '1': [examples[0]],
        '2': examples.slice(0, 2),
        '3': examples.slice(0, 3),
        '4': examples.slice(0, 4),
        '6': examples,
      },
    },
  },
} satisfies Meta<typeof MediaGrid>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Base: Story = {
  args: {
    media: examples.slice(0, 3),
    onPress: fn(),
    preferredLayout: 'horizontal',
    objectFit: 'scale-down',
  },
};
